"""
Everybody Codes 2024
Quest 1, Part 1
"""

input_str = (
    "BCBBBBAAABABBCACACCABBCBCCBBABBAACBCCACBAABBCCCCBCABCBBBBBBAAACBABACCBBBC"
    "BBCBAAAAAABAAAABBAAABBBBBBABCABCAABBCACCBBACBBCBABBAABABAACCACCCBABCCBABC"
    "AAAABBACACCBCACBAACCCCCBBCCCACBABBBABBBCCBABAACBBACCACBCBBACCBBABBABABBBB"
    "BBABBBBCACCABACABCBBBBBCBCCCCABBCBABCAAACACABABCBACACACBCBBACAAABAABACACA"
    "CACBABBAAAAABBBABCABABACBAABCACCACCAAAACCCCABCCAABCCCAACBCBBCAABBAACCCBAA"
    "ACCBABCABCBACCCBBCBAACAACABBBACAAACBBCCAACCCACBABCACABBABBBBCCCCAAABCACCB"
    "AAACACBCABBCCCBABBCCCCBBCCACAABAAACAAACBBBBBCBCCCCCCCCCAAACCCACBBABACABCB"
    "ACCAACBCAAACABCAAAACACBACBBCBBCCBAACACACCCAABBABBCCBCBBBACCCBCBBCCABAABAB"
    "CBBACCAAAABBCCCCAAABCABBCBBAAAABBBACBACBBBCCACAAACCCCBCBCBBBABCCBBAAACABC"
    "AACAAAACAACBBBABAAAABCBAABCCAABCAABCBABAABCBCCBABCBBBBBBAABBCCAACABCABAAB"
    "ACBCABCABCACAAABCCAABAABBBAABBBCAACCACABBCBCCACBCBAAAAACAABBACBCCBAACCAAB"
    "ACBAAAACCABACACACAABBACCBBCCCACCBBCACBBCBBAAAAACBBCACBCCAABBBBCACAABBACCB"
    "CCCBBBACBABCCBACCAABAACACCCCACBBACBCCACBCBABBABABABABAABBACCCABCCAACBCBCA"
    "CCABBACACBAACABCCAABBBACCCABACCAACACACAACCCCCCBBCBB"
)

def get_value(letter: str) -> int:
    if letter == 'A':
        return 0
    if letter == 'B':
        return 1
    if letter == 'C':
        return 3
    else:
        raise ValueError('Letter must be A, B, or C!')

values = [get_value(letter) for letter in input_str]

total = sum(values)

print(f"Answer: {total}")
